services:
  - type: web
    name: socialbuddy-backend
    runtime: docker
    rootDir: backend

    envVars:
      - key: GEMINI_API_KEY
        sync: false

      - key: OCR_SPACE_API_KEY
        sync: false