import React, { useState } from 'react';
import { Sparkles, Copy, Check, Wand2 } from 'lucide-react';

interface ImprovedPostProps {
  content: string;
}

export const ImprovedPost: React.FC<ImprovedPostProps> = ({ content }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      // fallback for clipboard failure
    }
  };

  return (
    <div className="bg-white border border-indigo-50 rounded-2xl p-6 flex flex-col gap-4 shadow-sm">
      {/* Header */}
      <div className="flex items-center gap-3">
        <div className="p-2 rounded-xl bg-indigo-50 border border-indigo-100">
          <Wand2 className="w-4 h-4 text-indigo-600" />
        </div>
        <div>
          <h3 className="text-sm font-bold text-slate-800">AI-Optimized Copy</h3>
          <p className="text-[11px] text-slate-500">Improved version of your post</p>
        </div>
        <button
          id="copy-improved-post"
          onClick={handleCopy}
          className={`ml-auto flex items-center gap-1.5 text-xs font-semibold px-3 py-1.5 rounded-xl border transition-all duration-200 ${
            copied
              ? 'bg-green-50 border-green-200 text-green-700'
              : 'bg-indigo-50 border-indigo-100 text-indigo-600 hover:bg-indigo-100 hover:text-indigo-700'
          }`}
        >
          {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
          {copied ? 'Copied!' : 'Copy'}
        </button>
      </div>

      {/* Content Area */}
      <div className="relative">
        {/* Sparkle decoration */}
        <div className="absolute top-3 right-3 opacity-30">
          <Sparkles className="w-4 h-4 text-indigo-500" />
        </div>

        <div className="bg-slate-50 border border-slate-100 rounded-xl p-4 min-h-[180px]">
          <pre className="text-sm text-slate-700 font-sans whitespace-pre-wrap leading-relaxed break-words">
            {content}
          </pre>
        </div>
      </div>

      {/* Footer hint */}
      <p className="text-[11px] text-slate-400 flex items-center gap-1.5 font-medium">
        <Sparkles className="w-3 h-3 text-indigo-500" />
        Generated by SocialBuddy.ai — Edit before posting
      </p>
    </div>
  );
};
